services:
  api:
    # container_name: api
    image: node:14
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
      - '9229:9229'
    working_dir: /home/node/app
    volumes:
      - ./lambda:/home/node/app
    environment:
      NODE_OPTIONS: --inspect=0.0.0.0:9229 --enable-source-maps
      DYNAMODB_ENDPOINT: "http://dynamodb:8000"
      DYNAMODB_TABLENAME: Cats
      DYNAMODB_REGION: eu-north-1
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
    command:
      - npm 
      - run
      - local
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8800:8000"
    volumes:
      - dynamodb:/home/dynamodblocal/data/
      # - "./docker/dynamodb:/home/dynamodblocal/data"
    command:
      - -jar
      - DynamoDBLocal.jar
      - -sharedDb
      - -optimizeDbBeforeStartup
      - -dbPath
      - ./data/
    working_dir: /home/dynamodblocal
    user: root
volumes:
  dynamodb: